### ISSUE TITLE
Hardcoded?

### ISSUE THREAD

**Issue by dinism** [JotaDF/moodle-block_game#11]
Thanks for the plugin.

I'm a PT-PT translator and i found this:
![imagem](https://user-images.githubusercontent.com/14828021/117891790-7660ac00-b2af-11eb-8a9a-7546ea1648dd.png)

Muito OBRIGADO

**Comment by dinism** [comment]
That's an image. Desculpa.

**Comment by JotaDF** [comment]
Obrigado por relatar! É uma imagem, mas mesmo assim vou corrigir! 
Agradeço

**Comment by dinism** [comment]
Viva

Será possível alterar a string em inglês? Muito OBRIGADO
