### ISSUE TITLE
Comportamento estranho?

### ISSUE THREAD

**Issue by dinism** [JotaDF/moodle-block_game#12]
Quando se clica no avatar para alterar aparece "algo estranho" atrás do avatar.
![block_game](https://user-images.githubusercontent.com/14828021/118390261-0c853100-b626-11eb-973b-02705bea3c52.gif)

O rodapé da minha página, tema Boost
![imagem](https://user-images.githubusercontent.com/14828021/118390336-67b72380-b626-11eb-8f0f-3094cbd8d3c8.png)

Quando estamos a ver a informação do utilizador, a parte das medalhas "tapa" o rodapé.

![block_game_2](https://user-images.githubusercontent.com/14828021/118390387-b5cc2700-b626-11eb-9366-f7c217d4cdaa.gif)
Is this OK?
MUITO OBRIGADO

**Comment by JotaDF** [comment]
Olá Dinis Medeiros,
Obrigado pelas observações. 
Na página do perfil estava faltando uma div e no link do avatar eu tive que mudar para input image pois aparecia aquela barra atrás porque é uma imagem SVG.
Vou postar essas correções.

Mais uma vez, obrigado!
