### ISSUE TITLE
Palavra erada.

### ISSUE THREAD

**Issue by GilbertVilalva** [JotaDF/moodle-block_game#13]
![Erro](https://user-images.githubusercontent.com/42963600/160632401-93582c2e-d25e-428a-a76e-c7c8f1f791d0.PNG)

Quando clicamos para a pontuação ser resetada a palavra está escrita de forma incorreta. O certo seria "perderão".

**Comment by JotaDF** [comment]
Gilbert, A tradução é feita diretamente no moodle.org.
