### ISSUE TITLE
Issue with activity setting in Moodle 4.0.4

### ISSUE THREAD

**Issue by mattgig** [JotaDF/moodle-block_game#19]
When I install (update) the newest version of the Game Block (1.3.1) plugin in Moodle 4.0.4+ I get an error as soon as I try to change settings in activities such as quizzes or databases.

Coding error detected, it must be fixed by a programmer: The 'name' value must be set in other.
[More information about this error](http://docs.moodle.org/400/en/error/debug/codingerror)
Debug info:
Error code: codingerror×Dismiss this notification
Stack trace:
	• line 136 of /lib/classes/event/course_module_updated.php: coding_exception thrown
	• line 272 of /lib/classes/event/base.php: call to core\event\course_module_updated->validate_data()
	• line 161 of /lib/classes/event/course_module_updated.php: call to core\event\base::create()
	• line 693 of /course/modlib.php: call to core\event\course_module_updated::create_from_cm()
	• line 168 of /course/modedit.php: call to update_moduleinfo()

Despite the error, the settings are still changed.

I could replicate this behaviour on two different instances. As soon as I deinstall the plugin, the error disappears.

Steps

1. Install or update the plugins to version 1.3.1
2. Go to an activity and choose settings.
3. Save the settings.
4. The error is thrown. (Setting are saved.)

Could you please check whether you can replicate that behaviour?

**Comment by JotaDF** [comment]
I tried to replicate the error here in my environment, following your steps, but I couldn't. We made some changes with a possible solution. The update is already in the moodle.org directory! Install and see if it solves your problem.

**Comment by mattgig** [comment]
Your new version has solved the problem. No more error messages. Thank you for your quick reaction.
